# coding=utf8

# Copyright 2018 JDCLOUD.COM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This class is auto generated by the jdcloud code generator program.


class HostPolicy(object):

    def __init__(self, host, uri, subsetId, servicePort=None):
        """
        :param host:  接入域名
        :param uri:  uri前缀
        :param servicePort: (Optional) 服务端口
        :param subsetId:  逻辑子集ID
        """

        self.host = host
        self.uri = uri
        self.servicePort = servicePort
        self.subsetId = subsetId
